apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    {{- include "compss-app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: {{ .Values.compss.master.ports.name }}
  {{- if eq .Values.compss.master.prometheusClient.enabled true }}
  - name: prometheus
    protocol: TCP
    port: {{ .Values.compss.master.prometheusClient.containerPort }}
    targetPort: prometheus
  {{- end }}
  selector:
    app: {{ .Release.Name }}