apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    {{- include "compss-matmul.labels" . | nindent 4 }}
spec:
  type: NodePort  # Change to NodePort for external access
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: {{ .Values.compss.master.ports.name }}
  - name: prometheus
    protocol: TCP
    port: 15000
    targetPort: prometheus
  - name: mqtt
    protocol: TCP
    port: 1883             # External port
    targetPort: mqtt       # Maps to containerPort: 1883
    nodePort: 31883       # Optional: Manually specify a NodePort
  selector:
    app: {{ .Release.Name }}