{{- if .Values.intents.enabled }}
apiVersion: "ido.intel.com/v1alpha1"
kind: Intent
metadata:
  name: {{ .Values.intents.intent.name }}
spec: 
  targetRef:
    kind: "Deployment"
    name: "{{ .Release.Namespace }}/{{ .Release.Name }}-worker-0"
  objectives:
    - name: {{ .Values.intents.intent.objectives.name }}
      value: {{ .Values.intents.intent.objectives.value }}
      tolerance: {{ .Values.intents.intent.objectives.tolerance }}
      measuredBy: {{ .Release.Namespace }}/{{ .Values.intents.intent.objectives.measuredBy }}

---
apiVersion: "ido.intel.com/v1alpha1"
kind: KPIProfile
metadata:
  name: {{ .Values.intents.KPIProfile.name }}
spec:
  type: "{{ .Values.intents.KPIProfile.type }}"
  description: "{{ .Values.intents.KPIProfile.description }}"
  query: "{{ .Values.intents.KPIProfile.query }}"
  props:
    endpoint: "{{ .Values.intents.KPIProfile.props.endpoint }}"
{{- end }}