apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: master-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: master-sa
roleRef:
  kind: Role
  name: master-role
  apiGroup: rbac.authorization.k8s.io