apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-master
spec:
  selector:
    app: {{ .Release.Name }}
    role: master
  ports:
  - name: port-43100
    protocol: TCP
    port: 43100
    targetPort: 43100-port