apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: monitoring-prometheus-lw79p
    {{- include "compss-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "compss-app.labels" . | nindent 4 }}
  endpoints:
  - port: prometheus
    interval: 20s
    scrapeTimeout: 10s
    path: /metrics
    scheme: http